version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ocr-api:cpu
    environment:
      - LOG_LEVEL=INFO
      - MAX_UPLOAD_MB=15
      - RATE_LIMIT=120/minute
    ports:
      - "8000:8000"
    restart: unless-stopped

  # Serviço opcional para GPU (ative com: docker compose --profile gpu up)
  api-gpu:
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: ocr-api:gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - LOG_LEVEL=INFO
      - MAX_UPLOAD_MB=20
      - RATE_LIMIT=200/minute
    ports:
      - "8001:8000"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped